### ISSUE TITLE
[Q] ERROR Python 'pickledobject' cannot be converted to a MySQL type

### ISSUE THREAD

**Issue by PsychicSmurf** [GDay/django-q2#27]
I thought initially that this was down to using a version of Django/Python that wasn't supported by the previous Django-Q but this issue remains in Q2 although I cannot work out where the issue lies - With Django-Q, Picklefield or MySql-Connector.

Library Versions:
```
    django-picklefield 3.1
    Django 4.0.4
    django-q2 1.4.2
    python 3.10.7
    mysql-connector-python 8.0.29
```
   
Fresh installation. Scheduler works correctly - i.e. the task completes - however it fails just after when it tries to create a log entry about the success/failure.

```
Q_CLUSTER = {
'name': 'DjangORM',
'workers': 4,
'timeout': 90,
'retry': 120,
'queue_limit': 50,
'bulk': 10,
'orm': 'default'
}
```

For each scheduled task I see 5 similar log entries:

```
10:25:18 [Q] INFO Enqueued 4
10:25:18 [Q] INFO Process-1 created a task from schedule [2]
10:25:19 [Q] INFO Process-1:2 processing [friend-wyoming-kilo-king]
10:25:20 [Q] ERROR Python 'pickledobject' cannot be converted to a MySQL type
10:25:20 [Q] INFO Processed [friend-wyoming-kilo-king]
```

The django_q_schedule table gets an entry when I schedule a task.
All three django-q DB tables are empty once the task completes.

**Comment by GDay** [comment]
This is very strange. I have a feeling this has to do with the `mysql-connector-python`. What "engine" did you use in the "DATABASES"? I couldn't get it connected with that library.
I just ran a test with the latest version of Django-q2 and created a simple django project in it and connected it to the mysql that I have running in docker (mysql 8). Both the app and mysql run in docker.

This is my DATABASES setting in `settings.py`:
```
DATABASES = {                                                                                                                                                                                                                    
    'default': {                                                                                                                                                                                                                 
        'NAME': 'db',                                                                                                                                                                                                            
        'ENGINE': 'django.db.backends.mysql',                                                                                                                                                                                    
        'HOST': 'mysql',                                                                                                                                                                                                         
        'PORT': 3306,                                                                                                                                                                                                            
        'USER': 'user',                                                                                                                                                                                                          
        'PASSWORD': 'password',                                                                                                                                                                                                  
        'OPTIONS': {                                                                                                                                                                                                             
            'autocommit': True,                                                                                                                                                                                                    
        },                                                                                                                                                                                                                       
    }                                                                                                                                                                                                                            
}
```
I used this library: https://pypi.org/project/mysqlclient/ to get mysql to connect and it ran async tasks without any issues.

**Comment by PsychicSmurf** [comment]
For the `mysql-connector-python` package to my MariaDB/MySQL database I was using this engine:

`'ENGINE': 'mysql.connector.django'`

After installing `mysqlclient`, changing the engine config, and re-running the app, everything works perfectly as you say, so it's definitely a connector issue.

Thank you. 

My issue has now gone away, and the issue is certainly not with Q2.  It is certainly strange that the other connector fails in this way, especially aa it's the official MySQL one, and yet works perfectly for anything else I've done.

**Comment by GDay** [comment]
Awesome. Thanks for letting me know. Good to hear that it got solved with that. 
Indeed weird that the driver was the issue.

FWIW: Django seems to recommend the `mysqlclient` library as well: https://docs.djangoproject.com/en/4.1/ref/databases/#mysql-db-api-drivers
