### ISSUE TITLE
Bimonthly programming

### ISSUE THREAD

**Issue by N1K1TAS95** [GDay/django-q2#35]
Hi!
I was wondering if it's possible to add Bimonthly schedule type to the Schedule object.
I'm making an expenses tracker and here in Italy our bills are usually bimonthly. I'm using Django Q for automatic insertion of expenses.
For now, I got around the problem with CRON type for the schedule, `0 0 1 */2 *`.

**Comment by GDay** [comment]
Thanks for the suggestion. Both biweekly and bimonthly will be added when I merge #36. Need to fix translations before I can merge that. Should be released later this week.

**Comment by N1K1TAS95** [comment]
> Thanks for the suggestion. Both biweekly and bimonthly will be added when I merge #36. Need to fix translations before I can merge that. Should be released later this week.

Thanks!!!

**Comment by GDay** [comment]
Update to at least 1.4.5 and you will have it available!

Docs: https://django-q2.readthedocs.io/en/master/schedules.html#django_q.Schedule.BIMONTHLY

**Comment by N1K1TAS95** [comment]
> Update to at least 1.4.5 and you will have it available!
> 
> Docs: https://django-q2.readthedocs.io/en/master/schedules.html#django_q.Schedule.BIMONTHLY

Thanks!!!
