### ISSUE TITLE
next_run gets calculated wrong for timezones that have daylight saving time (DST)

### ISSUE THREAD

**Issue by Grayknife** [GDay/django-q2#44]
Hi, I found this fork of django q. Thanks for maintaining django-q!

I have got some problems using the scheduler and the calculated next_run in my timezone (germany), because we have daylight saving time. 
I want to create a schedule that runs every day at 6am (german time). It will be stored as `2022-10-01 04:00` UTC in the database if I create that schedule in summertime (UTC+2). 
Now its wintertime (UTC+1) the schedule should still run every day at 6am (german time), but instead it runs at 5am (german time), because the datetime in the database is still `2022-11-01 04:00` UTC (and not adjusted to `2022-11-01 05:00` UTC).

Django settings are the following:
```
TIME_ZONE='UTC'
USE_TZ=True
```
Changing the settings to `TIME_ZONE='Europe/Berlin'` does not fix the problem and django documentation also suggests that I should not change this setting.

Have you or anynone encountered such problem?

**Comment by GDay** [comment]
Thanks for reporting this! 

Two questions: 
- Could you show me the schedule you are running? I am mainly curious if you are using any of the build-in schedules or if you are using the cronitor package in addition to this package.
- Did you have the same issue with the old package? (if you ever used that)

Django-q (the old version) uses Arrow to calculate some of the datetimes. I have removed that package from this library, maybe that messed with the timezones a little.

Thanks!

**Comment by Grayknife** [comment]
Thanks for reply! 

1. question: I am using the build-in schedules (WEEKLY)
2. question Yes, I encountered that problem in the old version also. I also found a related ticket to that topic in the old repo here: https://github.com/Koed00/django-q/issues/630 

Sidequestion: Why did you remove the arrow package?

**Comment by GDay** [comment]
Okay thanks. This should be a fairly easy fix. Will get back to this in the next few days. 

> Sidequestion: Why did you remove the arrow package?

There were only two places where this library was used. It was easy enough to create two small functions that handled the things that Arrow handled for us in this library. In general, I like to keep things simple and not add more dependencies than absolutely necessary.

**Comment by GDay** [comment]
Oh, that's a good idea! Will do that!

**Comment by SebastianRehfeldt** [comment]
Hey! First of all, Thanks a lot for your work on django-q2! 

> Have you or anynone encountered such problem?

Yes, We are having the same issue with running DAILY schedules in Germany. The suggested solution via Q_CLUSTER config works for us too and is very appreciated :)

**Comment by GDay** [comment]
@SebastianRehfeldt @Grayknife Sorry for the delay on this. I forgot how annoying dealing with timezones is, haha.

In any case, this fix has been released under v1.4.7.

See test here:
https://github.com/GDay/django-q2/blob/cf33275d92ecb510aa0a63ac1432dd92b06856ef/django_q/tests/test_scheduler.py#L87-L141

Docs: https://django-q2.readthedocs.io/en/latest/configure.html#time-zone

**Comment by Grayknife** [comment]
Feel you, i also hate timezones...

Thank you very much for your fix!
