### ISSUE TITLE
django-q still required

### ISSUE THREAD

**Issue by jimjag** [GDay/django-q2#50]
To use, both django-q and django-q2 must be installed. If just Q2 is installed, and one tries to pull from the module, you get the error:

```
    from django_q.tasks import async_task, schedule
ModuleNotFoundError: No module named 'django_q.tasks'
```
This implies:

```
pip install django-q
pip install django-q2
```

**Comment by GDay** [comment]
Something must have gone wrong there, but `django-q` is definitely not necessary for `django-q2`. Those are two independent packages. 

I have been using django-q2 without django-q in production without issues:

https://github.com/chiefonboarding/ChiefOnboarding/blob/2410942a5522076d643f9b995b717de7e95f1dd2/back/Pipfile#L6-L27

**Comment by jimjag** [comment]
Using pipenv, a complete removal and then update of the venv was required.
