### ISSUE TITLE
Clarify which database connection should be used with the orm broker and fix related issues

### ISSUE THREAD

**Issue by msabatier** [GDay/django-q2#60]
When the orm broker was introduced (https://github.com/Koed00/django-q/commit/2bffcf554b962d5e38cc689afac6f2ab690cdebf) the Conf.ORM database connection was only used to access the broker Queue (class OrmQ).

While trying to solve an - in fact unrelated - issue a merge request https://github.com/Koed00/django-q/pull/561 introduced the HAS_REPLICA flag and at the same time started to use the Conf.ORM database connection to also access other objects (Success and Schedule).

This introduced new issues, see https://github.com/Koed00/django-q/issues/558#issuecomment-869049021

In order to properly fix this we should first clarify how the database for django-q is chosen when the orm broker is used.

I see 3 possibilities :

1. Go back to the original behavior and limit the use of Conf.ORM database connection to only the OrmQ class. This would imply
    - fix the selection of the database for objects other than OrmQ (use db.router.db_for_write() on the correct object where needed see https://github.com/Koed00/django-q/issues/558#issuecomment-873027786)
    - remove Conf.HAS_REPLICA
2. Use the django standard way which is to use the default connection or define a custom db.router for more complex scenarios. This would require
    - transform Conf.ORM into a boolean just used to define if we want to use the ORM as a broker (instead of redis or other broker)
    - remove Conf.HAS_REPLICA 
3. Use the Conf.ORM database connection consistently for all django-q objects. 
     - this would be a much bigger code change
     - the Conf.HAS_REPLICA would be used to still be able to use a db.router (possibly renaming the option to something more explicit)

Let me know what you think is your preferred solution and I will then prepare a PR

**Comment by GDay** [comment]
Interesting issue. I will get back to this in 48 hours when I have a bit more time to take a look at this. Thanks for putting this together and willingness to work on a PR!

**Comment by GDay** [comment]
I think 1 is a very reasonable solution!

Thanks!

**Comment by msabatier** [comment]
Great, I just created the PR #61

**Comment by GDay** [comment]
closed by #61
