### ISSUE TITLE
Can't upgrade to v1.4.10

### ISSUE THREAD

**Issue by Kimor-hello** [GDay/django-q2#68]
Hello, 

Friday our dependabot created a Pull Request in order to upgrade django-q2 from 1.4.9 to 1.4.10, unfortunately this is not working.
 
Here is the stack trace:

```
Collecting django-q2==1.4.10
  Using cached django_q2-1.4.10.tar.gz (73 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package django-q2 produced metadata for project name django-q. Fix your #egg=django-q2 fragments.
Discarding https://files.pythonhosted.org/packages/dc/3b/d3f083622f49a4a316e722c8b2fda9a0ecff7e8b5d11e3cffa6450db7a27/django_q2-1.4.10.tar.gz (from https://pypi.org/simple/django-q2/) (requires-python:>=3.8.14,<4): Requested django-q from https://files.pythonhosted.org/packages/dc/3b/d3f083622f49a4a316e722c8b2fda9a0ecff7e8b5d11e3cffa6450db7a27/django_q2-1.4.10.tar.gz (from -r requirements.txt (line 20)) has inconsistent name: expected 'django-q2', but metadata has 'django-q'
ERROR: Could not find a version that satisfies the requirement django-q2==1.4.10 (from versions: 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10)
ERROR: No matching distribution found for django-q2==1.4.10
```

I am using python3.10 and pip 22.3.1.

Any ideas on how to fix it ? 

Thanks :)

**Comment by GDay** [comment]
> ERROR: Could not find a version that satisfies the requirement django-q2==1.4.10 (from versions: 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, **1.4.10**)

Uh? That's weird, it's right there. Will take a look when I have a minute to spare. Thanks for creating this issue.

**Comment by GDay** [comment]
The setup file was missing. I accidentally broke that while trying to get the translation files to work. The tests don't cover that, so that's why it went unnoticed. I have removed that part again, will take another look at the translation files later.

Should be good to go now in version 1.4.11!
